from typing import Any


class IApp:
    async def pre_update_async(self, name: str = ..., order: int = ...) -> float: ...
    async def next_update_async(self, name: str = ..., order: int = ...) -> float: ...
    async def post_update_async(self, name: str = ..., order: int = ...) -> float: ...
    def get_extension_manager(self) -> Any: ...
    def is_running(self) -> bool: ...
    def update(self) -> None: ...


def get_app() -> IApp: ...
def get_app_interface() -> IApp: ...
